version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/go-template cmd/main.go
    desc: Start DB server + liquibase cli using Docker
  test:
    cmds:
      - go mod tidy
      - go test ./...
      - go vet ./...
    desc: Run tests and vetting